hash-format = "sha256"

[[files]]
file = "mods/async.pw.toml"
hash = "bbfcf4aa5a3887dca532da7ea1469c994f01ee0685afcf46961a582aed4f4e6d"
metafile = true

[[files]]
file = "mods/better-beacon-placement.pw.toml"
hash = "5d223e192142234d38f02eef2c84a77cc0ab5948420320f37095fd730fc042e4"
metafile = true

[[files]]
file = "mods/better-conduit-placement.pw.toml"
hash = "15df5259e76d9273607d547736cff66ae9dd0bf12e8f1a5b4749aebff727de31"
metafile = true

[[files]]
file = "mods/better-spawner-control.pw.toml"
hash = "c16228582cf4653b52973fabc8375cf995094e6b2e5b1883ce2d9acd7a3e58fb"
metafile = true

[[files]]
file = "mods/blasting-plus.pw.toml"
hash = "461c3abf9f0a3932cca35f658f06176aa5e41cf7e27116295be361a91592e1e1"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "1aea3582fca46964d38d5746c4c6953a4235ac5aecd73321f63d1fadad38da63"
metafile = true

[[files]]
file = "mods/bluemapvisabilitytoggle.pw.toml"
hash = "2ec72749073876ea2806708a3516d3461f72a501234e0e3287a3d7952a1c1695"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "6ffdf05e661acb9275b908ee63cd62330ca65bd732d71b2f9b6b99bb763f2e2b"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "ed55fdea501426bbabdbe8f3ed4440158a17c435b978d5d38b4a926e53cdfd6f"
metafile = true

[[files]]
file = "mods/choicetheorems-overhauled-village.pw.toml"
hash = "022682338a49c1ed7ad5ea5b144020c18aae0fdb0dbcea452c70808bbd682179"
metafile = true

[[files]]
file = "mods/chunky-player-pause.pw.toml"
hash = "36f19df1c093e366eb4ab1aebe5f0c71acb58e8ff4e9a8036f6c0aa7a72e47e0"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "125d5f809e1fa06715bbb585463dd845cb256c69c901655a2e9f80dae99348e2"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "6b408e7b83e9b769fcafe9216c6f6a528d8930c6d34f7984a9e42119b5ac7d44"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "b78d967639e2a111321692ed27de64f73dbf34509fd7cc7381e1b2d440570a03"
metafile = true

[[files]]
file = "mods/conduits-prevent-drowned.pw.toml"
hash = "3ab8db8add6b106735f131dc8da1497b8e88b79d2694a3b75eda67ba17b32b97"
metafile = true

[[files]]
file = "mods/configurable.pw.toml"
hash = "0f3ffd57a60c436b364fa7d68cd705b2083e3049d08a0b420e557688de6aeb91"
metafile = true

[[files]]
file = "mods/death-counter.pw.toml"
hash = "dc56c94d702e64e0e31ca53f0c52be188a931e6a4e4f48e932df4a32a1a43b5a"
metafile = true

[[files]]
file = "mods/dragon-drops-elytra.pw.toml"
hash = "40349027e36cd727f3ded0c7e65cfb9fce858c1d86626f32abdaf301f4e7ca23"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "d610b134091e600f2b03ef2969285cfd195783481974b2af76fe4bd71f055980"
metafile = true

[[files]]
file = "mods/entity-health-bars.pw.toml"
hash = "691e2b17050c16cdb8396a8cc732b612ce355d7a515940dc1a1f1d212749c420"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "44a738454b7ecce0a19c3efa928fe0651dc0e327ded942bf51970c49ff0c9592"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "bcd03e49bc0fbfdd27480880ed0cd227fc17b90502cdc99a047ef74f3302a5fe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "3f5eab6c74f8a622faccb7be82d522ed4db2c0e45166182d76fcfe1425ea5783"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "7ed8df687dc5d9229b3eabc08e8ef9c0bc3825d0f75736c53c1470adf43b4217"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d9d10b2dc49123934063ba3454f7e703267bc812504e2c34bff5d0a16e0b4109"
metafile = true

[[files]]
file = "mods/floodgate.pw.toml"
hash = "7a50c606177a8d4269f69df87f74e7caf1f8ff28bc523f015503ed3fb3d8c274"
metafile = true

[[files]]
file = "mods/followers-teleport-too.pw.toml"
hash = "1f6197f171ef27ddc8f3d843e97e8fd7f72431edd0db2d67794fc93c9b6efe4c"
metafile = true

[[files]]
file = "mods/frostbytes-skip-server-movement-check.pw.toml"
hash = "8e77376ef19cd85e63b906fda70c84d1e5179e65f802dd91fe4d9742c606d3da"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "cfe2373a438fb2256004f5da5b35751b3d19f7516f525e2494af68cbd07fa284"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "be43c57bfbee5b9c2befe5fc21b364accd816902211dbaae2c4c01ee36376af4"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "fb9875e2b7dc4e262ecdeb9ce59da39d260424f2bca819eb33fd727ddb988358"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "4b8f60035bbc046b7ea9ea64c667430fa07e94b885a547dc0405f9b54ead31c1"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
hash = "4881e1002094ef85e0634cca5abf5e0025de5277efcfc82e9753ba1f3defa9f6"
metafile = true

[[files]]
file = "mods/mine-spawners.pw.toml"
hash = "1e2f0297dad9a97b3adeff61b862d148d8cb03875736feace77d8e4d90b35e6a"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "c37d131c6416ddec09d9631a955787e39f9c5292900ee2d4a4e0ada8bce379ff"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "fcb043269323364be8492780e58fe66e2d48d40f2749f7fec358ae25e1f1467a"
metafile = true

[[files]]
file = "mods/no-animal-tempt-delay.pw.toml"
hash = "4378c26b6eed5e227d82cac44f1dbf9df2520e307d561f4765de0244d132be6b"
metafile = true

[[files]]
file = "mods/nofun-dnt.pw.toml"
hash = "ae846ab77fa3ac719c2da5b4adb1b324c21d43e3790e03c895ad4c646830816f"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "4b4e1a3584ee09be35a7a37148d8db6a530f9ffa35655278e8ab44db7a1b2c89"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "48f103be7ec99b3fd9328f2e0b8443b8277101cb89b13f708d992dc3532e8810"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "ab0e113320f3b5d095dae429a5efc409194365530a5b067cb55a7af46493fc49"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "619b9c6bcaddcd4fe602a5f11614b53290c5217694b6dd3255217f62695d3d91"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "c73f5c821d96c99c7241047a7691b6a6172ee86534b92107dfdbef86ecff8ea8"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "e1fc9f4f34557a5bb2ea5013dcd2c162e3b4ae4b20a9948ea79ba1de5e24e7e2"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "621e56ad677649509141a20b4a4a6042ea30af69c1527153681f8f2c4cf0104b"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
hash = "b87bc045dc42bb523c09b330f65b47f401b5c80894dfa6e95cf06baf21b2060e"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "be22b82e1acf08ef74267059a921faa9b2fafd2458225228cf43b34f943c395d"
metafile = true

[[files]]
file = "mods/tabtps.pw.toml"
hash = "f8412b671c261bc12d4fbb25b4c4756cb4adc8130d42272922ac9d1f1b7747b7"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "13f5f18356dfaa92b0026ba348fbb39a519531d6a0fb78ee3dc101b5529a3623"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
hash = "21cd5201f371ec356c637f9dc248445f0e183d5b11ac307ea041c11d0104c58b"
metafile = true

[[files]]
file = "mods/too-cheap.pw.toml"
hash = "d18df2496e7048d527f519658eeaab6def817c200f6e2ac9a635d89163052709"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "aa1242f91a1c16bb362a4decb6f127295bf2de133ebb34da1765192280c6d94d"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
hash = "9c5c2ba6a1884331927e7e1330ec935795d53ee3ac7785d2221b8d293530299a"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "77742d93823791eb8a30e389bc6ecfb04bd5206491006fa0b9bdf409c09e16d6"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "551a40e2b713b8a1ab70d7c08c3861e1c2cb186c3f6bd22087a207bf53bbb7e6"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "0dab920ec1f10d3feb95a9e952b61e2c64fc2bf6d4d2de49bef747a4283f718a"
metafile = true

[[files]]
file = "mods/when-dungeons-arise-seven-seas.pw.toml"
hash = "630293187d48345e6e91bae742958e8cfc65045d687522249a0fb1874b61b42b"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "05a86077d48ba789cec0c7b6e9f66735fa54159adfbc85071c5675110924be28"
metafile = true

[[files]]
file = "mods/wits.pw.toml"
hash = "9d411893f380b76479ecbd33eb9321737d82b8dd96283bba3de28f3f9f5597a2"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "def8e32b7170a037d164462793a80680c59ef292d073a4e3a51a645da1004044"
metafile = true
