hash-format = "sha256"

[[files]]
file = "mods/async.pw.toml"
hash = "bbfcf4aa5a3887dca532da7ea1469c994f01ee0685afcf46961a582aed4f4e6d"
metafile = true

[[files]]
file = "mods/better-beacon-placement.pw.toml"
hash = "5d223e192142234d38f02eef2c84a77cc0ab5948420320f37095fd730fc042e4"
metafile = true

[[files]]
file = "mods/better-conduit-placement.pw.toml"
hash = "15df5259e76d9273607d547736cff66ae9dd0bf12e8f1a5b4749aebff727de31"
metafile = true

[[files]]
file = "mods/better-spawner-control.pw.toml"
hash = "c16228582cf4653b52973fabc8375cf995094e6b2e5b1883ce2d9acd7a3e58fb"
metafile = true

[[files]]
file = "mods/blasting-plus.pw.toml"
hash = "461c3abf9f0a3932cca35f658f06176aa5e41cf7e27116295be361a91592e1e1"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "1aea3582fca46964d38d5746c4c6953a4235ac5aecd73321f63d1fadad38da63"
metafile = true

[[files]]
file = "mods/bluemapvisabilitytoggle.pw.toml"
hash = "2ec72749073876ea2806708a3516d3461f72a501234e0e3287a3d7952a1c1695"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "e68cf43a661587179a65ae4db8539d9bd100e60b7d7698fd506fd0e08c94155c"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "3de78cac66e41b29ab1f78ce4290d4b6f58eb4ab67e1363ce876fd5e376f9aff"
metafile = true

[[files]]
file = "mods/choicetheorems-overhauled-village.pw.toml"
hash = "022682338a49c1ed7ad5ea5b144020c18aae0fdb0dbcea452c70808bbd682179"
metafile = true

[[files]]
file = "mods/chunky-player-pause.pw.toml"
hash = "36f19df1c093e366eb4ab1aebe5f0c71acb58e8ff4e9a8036f6c0aa7a72e47e0"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "2dab2ad00cf7b98c872527be689e1036f1a9aeb6d3991e93e07428574931f9b1"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "48d24af6999874c87561bde62e6dd37c5c9ad67c343e318a21b75c3255302043"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "b78d967639e2a111321692ed27de64f73dbf34509fd7cc7381e1b2d440570a03"
metafile = true

[[files]]
file = "mods/conduits-prevent-drowned.pw.toml"
hash = "3ab8db8add6b106735f131dc8da1497b8e88b79d2694a3b75eda67ba17b32b97"
metafile = true

[[files]]
file = "mods/configurable.pw.toml"
hash = "689bd04256a9f89ca6318d55f7bce2452f4b8b7c7320cfe79343831cf9e4c846"
metafile = true

[[files]]
file = "mods/death-counter.pw.toml"
hash = "dc56c94d702e64e0e31ca53f0c52be188a931e6a4e4f48e932df4a32a1a43b5a"
metafile = true

[[files]]
file = "mods/dragon-drops-elytra.pw.toml"
hash = "40349027e36cd727f3ded0c7e65cfb9fce858c1d86626f32abdaf301f4e7ca23"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "d610b134091e600f2b03ef2969285cfd195783481974b2af76fe4bd71f055980"
metafile = true

[[files]]
file = "mods/entity-health-bars.pw.toml"
hash = "691e2b17050c16cdb8396a8cc732b612ce355d7a515940dc1a1f1d212749c420"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "44a738454b7ecce0a19c3efa928fe0651dc0e327ded942bf51970c49ff0c9592"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "bcd03e49bc0fbfdd27480880ed0cd227fc17b90502cdc99a047ef74f3302a5fe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "af8c1244254e85939ba3143c93cbbeabff8739566c345a16b63e6c2f20bf0a8c"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "44ce91936136fb30c08b2f062e6d92493f1f2cc5a526a8039b54d1ae3f61279c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d9d10b2dc49123934063ba3454f7e703267bc812504e2c34bff5d0a16e0b4109"
metafile = true

[[files]]
file = "mods/floodgate.pw.toml"
hash = "7a50c606177a8d4269f69df87f74e7caf1f8ff28bc523f015503ed3fb3d8c274"
metafile = true

[[files]]
file = "mods/followers-teleport-too.pw.toml"
hash = "1f6197f171ef27ddc8f3d843e97e8fd7f72431edd0db2d67794fc93c9b6efe4c"
metafile = true

[[files]]
file = "mods/frostbytes-skip-server-movement-check.pw.toml"
hash = "8e77376ef19cd85e63b906fda70c84d1e5179e65f802dd91fe4d9742c606d3da"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "270a4fc9cbfc34885e7ecda4b2547853acdb6dd3b95a614e1c34b3b5320c2743"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "be43c57bfbee5b9c2befe5fc21b364accd816902211dbaae2c4c01ee36376af4"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "ab786156dff86d3e781907cc4d415c1093f0a74da1815b2e8b0353806b25abca"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "4b8f60035bbc046b7ea9ea64c667430fa07e94b885a547dc0405f9b54ead31c1"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
hash = "1dde61332fc0dc654445b99f107c76bf61df2f398b1b5822d18b768e7becf5b6"
metafile = true

[[files]]
file = "mods/mine-spawners.pw.toml"
hash = "1e2f0297dad9a97b3adeff61b862d148d8cb03875736feace77d8e4d90b35e6a"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "9f9293ef5d8faf2abdd6e188b25ccb4287f2ceeb67fbc6403dbdbcdd5dba4dcd"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "bc59e692422d05a1cb4c6712c1ad1777bec427d458aa8ee73172631e021bacfb"
metafile = true

[[files]]
file = "mods/no-animal-tempt-delay.pw.toml"
hash = "4378c26b6eed5e227d82cac44f1dbf9df2520e307d561f4765de0244d132be6b"
metafile = true

[[files]]
file = "mods/nofun-dnt.pw.toml"
hash = "ae846ab77fa3ac719c2da5b4adb1b324c21d43e3790e03c895ad4c646830816f"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "b288b23c6932f66cc60420bc30276bd7bd315e1bf85f7e87ef1d1657d6ccef74"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "48f103be7ec99b3fd9328f2e0b8443b8277101cb89b13f708d992dc3532e8810"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "e68775ef8425e78c13655200d8525b8827901aecd9af4fe8be9f26c61a483d2d"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "619b9c6bcaddcd4fe602a5f11614b53290c5217694b6dd3255217f62695d3d91"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "c846f39e0e8e0127a1e1cb70320234a58c484961c5d978c46354e850d37371f4"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "8ea3dfa30999021bf9c0a0c9a369403f0d9cfeb40dc980a79d1a9f525d5ebc41"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "621e56ad677649509141a20b4a4a6042ea30af69c1527153681f8f2c4cf0104b"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
hash = "b87bc045dc42bb523c09b330f65b47f401b5c80894dfa6e95cf06baf21b2060e"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "be22b82e1acf08ef74267059a921faa9b2fafd2458225228cf43b34f943c395d"
metafile = true

[[files]]
file = "mods/tabtps.pw.toml"
hash = "f8412b671c261bc12d4fbb25b4c4756cb4adc8130d42272922ac9d1f1b7747b7"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "5fa8a9bdf7bed768403cc9d08436aae11770e93d29f34305258e1c65aa7b3bdf"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
hash = "21cd5201f371ec356c637f9dc248445f0e183d5b11ac307ea041c11d0104c58b"
metafile = true

[[files]]
file = "mods/too-cheap.pw.toml"
hash = "d18df2496e7048d527f519658eeaab6def817c200f6e2ac9a635d89163052709"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "aa1242f91a1c16bb362a4decb6f127295bf2de133ebb34da1765192280c6d94d"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
hash = "9c5c2ba6a1884331927e7e1330ec935795d53ee3ac7785d2221b8d293530299a"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "77742d93823791eb8a30e389bc6ecfb04bd5206491006fa0b9bdf409c09e16d6"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "551a40e2b713b8a1ab70d7c08c3861e1c2cb186c3f6bd22087a207bf53bbb7e6"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "0dab920ec1f10d3feb95a9e952b61e2c64fc2bf6d4d2de49bef747a4283f718a"
metafile = true

[[files]]
file = "mods/when-dungeons-arise-seven-seas.pw.toml"
hash = "630293187d48345e6e91bae742958e8cfc65045d687522249a0fb1874b61b42b"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "05a86077d48ba789cec0c7b6e9f66735fa54159adfbc85071c5675110924be28"
metafile = true

[[files]]
file = "mods/wits.pw.toml"
hash = "9d411893f380b76479ecbd33eb9321737d82b8dd96283bba3de28f3f9f5597a2"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "def8e32b7170a037d164462793a80680c59ef292d073a4e3a51a645da1004044"
metafile = true
