hash-format = "sha256"

[[files]]
file = "mods/async.pw.toml"
hash = "bbfcf4aa5a3887dca532da7ea1469c994f01ee0685afcf46961a582aed4f4e6d"
metafile = true

[[files]]
file = "mods/better-beacon-placement.pw.toml"
hash = "c349885d5c9430a551bb1a215453341f7a2ec1783f2715f5515f12fa606559e8"
metafile = true

[[files]]
file = "mods/better-conduit-placement.pw.toml"
hash = "4653bec041e6ddcb67491975153f53965ffc631124e8651c66fd3152ae8040de"
metafile = true

[[files]]
file = "mods/better-spawner-control.pw.toml"
hash = "493f636c1feec00004865460a1c94e5db85fb5fe7dc9f44792411c9e992cc5ee"
metafile = true

[[files]]
file = "mods/blasting-plus.pw.toml"
hash = "461c3abf9f0a3932cca35f658f06176aa5e41cf7e27116295be361a91592e1e1"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "17b8443e8c6808c914b4d18fd45b6aa12e8d6e46b8dd5516f68bcd9c97f2e09c"
metafile = true

[[files]]
file = "mods/bluemapvisabilitytoggle.pw.toml"
hash = "2ec72749073876ea2806708a3516d3461f72a501234e0e3287a3d7952a1c1695"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "94ff21a3cb20199350280ab4a1c1373a85fc641d87d0b7cb41a5b3af3d09e1b9"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "c6214a3903e034a911d984f84a98ad04fd7a0f76431d16986458ceb782b7d8c1"
metafile = true

[[files]]
file = "mods/choicetheorems-overhauled-village.pw.toml"
hash = "022682338a49c1ed7ad5ea5b144020c18aae0fdb0dbcea452c70808bbd682179"
metafile = true

[[files]]
file = "mods/chunky-player-pause.pw.toml"
hash = "36f19df1c093e366eb4ab1aebe5f0c71acb58e8ff4e9a8036f6c0aa7a72e47e0"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "075cf210e07a626d30a6b05aa523e2dc00446cc815d51911f636f73ceb879590"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b2103de7f3d13a7b7868890afd358e51f93bea4914e226fc0fbe53bdb84ff7e8"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3c6b206bface93aee9075a0c18c0ebe91026932610c52ae86489f1055342bbbf"
metafile = true

[[files]]
file = "mods/conduits-prevent-drowned.pw.toml"
hash = "84c5d550e2abd1281628d00225184fb567160d8f91aa7021b53fd7985b666e71"
metafile = true

[[files]]
file = "mods/configurable.pw.toml"
hash = "689bd04256a9f89ca6318d55f7bce2452f4b8b7c7320cfe79343831cf9e4c846"
metafile = true

[[files]]
file = "mods/death-counter.pw.toml"
hash = "dc56c94d702e64e0e31ca53f0c52be188a931e6a4e4f48e932df4a32a1a43b5a"
metafile = true

[[files]]
file = "mods/dragon-drops-elytra.pw.toml"
hash = "167c431731f1610a46319bdb84fa2515fe5e2024c680a7d498ebe0ef71413d36"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "c9ded64ac176018e78ac0340685b8607a4f01354e6090cddc8cfce7a73cbb90c"
metafile = true

[[files]]
file = "mods/entity-health-bars.pw.toml"
hash = "691e2b17050c16cdb8396a8cc732b612ce355d7a515940dc1a1f1d212749c420"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "8d38d6384680488a17754a9dd73dfa95880a451b62c5d6eb5290aaaa6fd41d96"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "bcd03e49bc0fbfdd27480880ed0cd227fc17b90502cdc99a047ef74f3302a5fe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fa8be992c1e3efbd030ef6a84409b766a936deb3fc3d06b657f8e468745044f0"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "44ce91936136fb30c08b2f062e6d92493f1f2cc5a526a8039b54d1ae3f61279c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4eb0060a2288f8f0f97e87eec65493e3e21f1f81ce6a6343e54ed296aadee957"
metafile = true

[[files]]
file = "mods/floodgate.pw.toml"
hash = "10d0a82638bf0b007845a92f58a1ffb81c4fafe71e8e836d5338961198d64b2e"
metafile = true

[[files]]
file = "mods/followers-teleport-too.pw.toml"
hash = "e84d010ee838b06a917f8eb2d3cc91d3c923591d1e1dbb1446827169026a49b8"
metafile = true

[[files]]
file = "mods/frostbytes-skip-server-movement-check.pw.toml"
hash = "8e77376ef19cd85e63b906fda70c84d1e5179e65f802dd91fe4d9742c606d3da"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "270a4fc9cbfc34885e7ecda4b2547853acdb6dd3b95a614e1c34b3b5320c2743"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5787b1deb7975af608901df0bf16b1e5de2452c98808f6a205c35aaa83e9f56a"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "07bcc3531e2629b2d4760685e1a87dc66172001f27d7899a3e10dc5ae31b49ba"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "2b49f28c7ca9d6c75fde3c1a8e8adbec1b6fb87a23f1e6765cd384ae5d29e713"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
hash = "1dde61332fc0dc654445b99f107c76bf61df2f398b1b5822d18b768e7becf5b6"
metafile = true

[[files]]
file = "mods/mine-spawners.pw.toml"
hash = "1e2f0297dad9a97b3adeff61b862d148d8cb03875736feace77d8e4d90b35e6a"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "9f9293ef5d8faf2abdd6e188b25ccb4287f2ceeb67fbc6403dbdbcdd5dba4dcd"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "bc59e692422d05a1cb4c6712c1ad1777bec427d458aa8ee73172631e021bacfb"
metafile = true

[[files]]
file = "mods/no-animal-tempt-delay.pw.toml"
hash = "e3eae9c377c0773eddd0728f0de9cd00c459cd026c747c8dcf504a4a8136edee"
metafile = true

[[files]]
file = "mods/nofun-dnt.pw.toml"
hash = "ae846ab77fa3ac719c2da5b4adb1b324c21d43e3790e03c895ad4c646830816f"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "b288b23c6932f66cc60420bc30276bd7bd315e1bf85f7e87ef1d1657d6ccef74"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "b0628ad24e9ea2d25a09b4f7be86d59a2c08e3c6ea22e6eb165bd5820e3a2401"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "d07dcf38f97eb948b4efa5a640a11712730f9ef25874f5f71293ebd579a55a62"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "619b9c6bcaddcd4fe602a5f11614b53290c5217694b6dd3255217f62695d3d91"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "bdb85673809c4d107cc01fb4810fea96b097a28d48b58e1e8c4b4c7034a8a91f"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "8ea3dfa30999021bf9c0a0c9a369403f0d9cfeb40dc980a79d1a9f525d5ebc41"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "621e56ad677649509141a20b4a4a6042ea30af69c1527153681f8f2c4cf0104b"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
hash = "b87bc045dc42bb523c09b330f65b47f401b5c80894dfa6e95cf06baf21b2060e"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "be22b82e1acf08ef74267059a921faa9b2fafd2458225228cf43b34f943c395d"
metafile = true

[[files]]
file = "mods/tabtps.pw.toml"
hash = "8b1ef62ce3d98494cfdb081a8b3ee113ba4ebc211d7909bf41878ec24c4f8807"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "5fa8a9bdf7bed768403cc9d08436aae11770e93d29f34305258e1c65aa7b3bdf"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
hash = "21cd5201f371ec356c637f9dc248445f0e183d5b11ac307ea041c11d0104c58b"
metafile = true

[[files]]
file = "mods/too-cheap.pw.toml"
hash = "6b6115895fe0ebbd9183941f3be07aed35867b4cfdc0d351dbfb59ec170785d7"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "c545f2d9b2cca20ead494fa706f32e6c0d610f1692b1d3269d574a838ab4e577"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
hash = "9c5c2ba6a1884331927e7e1330ec935795d53ee3ac7785d2221b8d293530299a"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "f9bbb787554239a92b6b15c028f3da00e5b048bdd0419ddda90cd2194ecb3069"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "2e38abe38877f59439b03178a0a177f90a7319c3a0a1f50332934adba36b24ea"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "73bd3e12b7f552db549143950fdd4df8c8429d9c1f65be9e21d9d1128f10e81b"
metafile = true

[[files]]
file = "mods/when-dungeons-arise-seven-seas.pw.toml"
hash = "630293187d48345e6e91bae742958e8cfc65045d687522249a0fb1874b61b42b"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "05a86077d48ba789cec0c7b6e9f66735fa54159adfbc85071c5675110924be28"
metafile = true

[[files]]
file = "mods/wits.pw.toml"
hash = "04021801736adcec148d9db10e445583f04cb0c7561f01315e58f3b49c50214a"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "39b4cccb2535a746e6597c84eaaa3052c0c20f2dd0704dfe853ffa5853dfb3d6"
metafile = true
