name = "ARC Unofficial"
author = "Defiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "052893544280eefaf7d983efa4b06e39caaf15be67a54e46260c8868738b29f0"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
