name = "ARC Unofficial"
author = "Defiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c8dbfdf85c388271dbb663f741d2f5c8a0cdb6d115fbab7494145d93cef3f3a"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
