name = "ARC Unofficial"
author = "Defiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa865bbd33520818d9fe0ac9f54f3eb224c58aed05953eedbde6e4e87b941dfe"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
