name = "ARC Unofficial"
author = "Defiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75c20bd0839682650a59b6a18173806a6f8fe3d9ae1cb32bf3bbfbf07db29107"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
