name = "ARC Unofficial"
author = "Defiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72d5ea4028efd99d3a4058d8f8ffcf55062efd19a8139d3083bb7bff3f04932c"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
